application: panwdbl
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /jobs/.*
  script: panwdbl.app
  login: admin

- url: /.*
  script: panwdbl.app

libraries:
- name: lxml
  version: "latest"